import margins from "../../styles/BoardMargin.module.css";
export const LeftMargin = () => {
  return (
    <div className={margins.container + " " + margins.left}>
      <svg
        xmlns="http://www.w3.org/2000/svg"
        version="1.1"
        className={margins.marginContent}
      >
        <text
          y="6.25%"
          x="50%"
          text-anchor="middle"
          dominant-baseline="central"
        >
          8
        </text>
        <text
          y="18.75%"
          x="50%"
          text-anchor="middle"
          dominant-baseline="central"
        >
          7
        </text>
        <text
          y="31.25%"
          x="50%"
          text-anchor="middle"
          dominant-baseline="central"
        >
          6
        </text>
        <text
          y="43.75%"
          x="50%"
          text-anchor="middle"
          dominant-baseline="central"
        >
          5
        </text>
        <text
          y="56.25%"
          x="50%"
          text-anchor="middle"
          dominant-baseline="central"
        >
          4
        </text>
        <text
          y="68.75%"
          x="50%"
          text-anchor="middle"
          dominant-baseline="central"
        >
          3
        </text>
        <text
          y="81.25%"
          x="50%"
          text-anchor="middle"
          dominant-baseline="central"
        >
          2
        </text>
        <text
          y="93.75%"
          x="50%"
          text-anchor="middle"
          dominant-baseline="central"
        >
          1
        </text>
      </svg>
    </div>
  );
};
